CREATE DATABASE database1;
USE database1;
CREATE TABLE T1(
ID INT PRIMARY KEY, FirstName VARCHAR(20), LastName VARCHAR(20)
);


CREATE TABLE T2(
RollNO INT PRIMARY KEY, SchoolName VARCHAR(20), Address VARCHAR(20)
);

INSERT INTO T1 VALUES (1, "Yakob", "Reta");
INSERT INTO T2 VALUES (2, "Jessica", "Lee");

SELECT * FROM T1;
SELECT * FROM T2;

ALTER TABLE T1 ADD CONSTRAINT fkID FOREIGN KEY (ID) REFERENCES T1(RollNO);



CREATE DATABASE STORE;
USE STORE;

CREATE TABLE CUSTOMERS(
	CID INT PRIMARY KEY,
    FULL_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50)
);

CREATE TABLE PRODUCTS(
	PID INT PRIMARY KEY,
    Product_Name VARCHAR(50) NOT NULL,
    Price DOUBLE NOT NULL
);

CREATE TABLE ORDERS(
	OID INT PRIMARY KEY,
    Order_DATE DATE NOT NULL,
    Order_quantity INT,
    CID_FK INT NOT NULL,
    PID_FK INT NOT NULL,
    FOREIGN KEY (CID_FK) REFERENCES CUSTOMERS(CID),
    FOREIGN KEY (PID_FK) REFERENCES PRODUCTS(PID)
);


INSERT INTO CUSTOMERS VALUES(1, "Yakob Reta", "YR@GMAIL.COM");
INSERT INTO CUSTOMERS VALUES(2, "Sara Yoseph", "YR@GMAIL.COM");
INSERT INTO CUSTOMERS VALUES(3, "Hana Reta", "YR@GMAIL.COM");

INSERT INTO PRODUCTS VALUES(1, "EARPHONES", 175.56);
INSERT INTO PRODUCTS VALUES(2, "SHOES", 249.99);
INSERT INTO PRODUCTS VALUES(3, "T-SHIRT", 25.00);


INSERT INTO ORDERS VALUES(1, "2024-05-23", 2, 1, 3);
INSERT INTO ORDERS VALUES(2, "2024-04-03", 1, 3, 2);
INSERT INTO ORDERS VALUES(3, "2024-01-08", 3, 2, 2);
INSERT INTO ORDERS VALUES(4, "2024-05-10", 5, 1, 1);


SELECT * FROM CUSTOMERS;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDERS;

